spring:
  rabbitmq:
    addresses: amqps://ecqdffqm:Br39splUn6tt2VW1MEw5aFWHu_60ZY9g@stingray.rmq.cloudamqp.com/ecqdffqm

queue:
  fiap: fiap.1scjr.mensagens

server:
  port: 8081

uri: http://localhost:8080/externalAccess